" --- GENERAL SETTINGS ---
set nocompatible           " Disable compatibility with vi
set encoding=utf-8         " Force UTF-8 encoding
filetype plugin indent on  " Load plugins according to detected filetype
syntax on                  " Enable syntax highlighting

" --- UI & VISIBILITY ---
set relativenumber         " Show relative line numbers
set number                 " Show current line number
set mouse=a                " Enable mouse support
set laststatus=2           " Always show statusline
set display=lastline       " Show as much as possible of the last line
set showmode               " Show current mode in command-line
set showcmd                " Show already typed keys
set list                   " Show non-printable characters

" Cursor Visibility
set cursorline             " Highlight the current horizontal line
set nocursorcolumn         " Ensure vertical column highlight is OFF

" --- CURSOR SHAPES (The Escape Code Fix) ---
" This forces Alacritty to change shapes by sending raw escape codes.
" 1 = Blinking Block
" 3 = Blinking Underscore
" 5 = Blinking Vertical Bar

" Insert Mode -> Blinking Bar
let &t_SI = "\e[5 q"

" Replace Mode -> Blinking Underscore
let &t_SR = "\e[3 q"

" Normal Mode (Exit Insert) -> Blinking Block
let &t_EI = "\e[1 q"

" --- INDENTATION ---
set tabstop=4              " Width of tab character
set shiftwidth=4           " Width of indentation
set expandtab              " Convert tabs to spaces
set autoindent             " Inherit indentation from previous line
set shiftround             " Round indent to multiple of shiftwidth
set backspace=indent,eol,start " Fix backspace behavior

" --- SEARCH ---
set incsearch              " Highlight while searching with / or ?
set hlsearch               " Keep matches highlighted
set wrapscan               " Searches wrap around end-of-file

" --- PERFORMANCE & WINDOWS ---
set ttyfast                " Faster redrawing
set lazyredraw             " Only redraw when necessary
set splitbelow             " Open new windows below
set splitright             " Open new windows to the right
set hidden                 " Allow switching buffers without saving
set report=0               " Always report changed lines
set synmaxcol=200          " Optimization: only highlight first 200 columns

" --- ICONS & CHARACTERS ---
if has('multi_byte') && &encoding ==# 'utf-8'
  let &listchars = 'tab:▸ ,extends:❯,precedes:❮,nbsp:±'
else
  let &listchars = 'tab:> ,extends:>,precedes:<,nbsp:.'
endif

" --- SHELL CONFIGURATION ---
" Fix issues when using Fish shell
if &shell =~# 'fish$'
  set shell=/bin/bash
endif

" --- BACKUP & DIRECTORIES ---
let s:backup_dir = $HOME . '/.vim/files/backup'
let s:swap_dir   = $HOME . '/.vim/files/swap'
let s:undo_dir   = $HOME . '/.vim/files/undo'
let s:info_dir   = $HOME . '/.vim/files/info'

if !isdirectory(s:backup_dir) | call mkdir(s:backup_dir, "p") | endif
if !isdirectory(s:swap_dir)   | call mkdir(s:swap_dir, "p")   | endif
if !isdirectory(s:undo_dir)   | call mkdir(s:undo_dir, "p")   | endif
if !isdirectory(s:info_dir)   | call mkdir(s:info_dir, "p")   | endif

set backup
let &backupdir = s:backup_dir
set backupext=-vimbackup
set backupskip=
let &directory = s:swap_dir . '//'
set updatecount=100
set undofile
let &undodir = s:undo_dir
let &viminfo = "'100,n" . s:info_dir . "/viminfo"
